repos:
  - repo: https://github.com/stoplightio/spectral
    rev: v6.13.2
    hooks:
      - id: spectral-lint
        files: ^openapi/specs/
  - repo: https://github.com/psf/black-pre-commit
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: v5.13.2
    hooks:
      - id: isort
